### ISSUE TITLE
Redis backup not suitable for PCF recovery, needs additional files

### ISSUE THREAD

**Issue by rguilme1** [pivotalservices/cfops-redis-plugin#1]
I am requesting that the Redis backup of the service broker contain the statefile.json file as indicated in these revised backup procedures:

[Redis Documentation](http://docs.pivotal.io/redis/maintain.html#backup)

I am trying to use cfops to recover PCF from bare metal.  So I need to recover all service brokers and their instance information in-sync with the Cloud Controller backup.  The Redis product team updated the backup / restore so the staefile.json is also included.   This provides the instance information that is needed when doing a bare metal recovery.

Can the plugin be updated to include this file in the backup?  I am ok with performing a manual restore.

Regards
  - Rick Guilmette

**Comment by kelapure** [comment]
👍  We need this at a number of customer sites for a functional REDIS backup

**Comment by calebwashburn** [comment]
Need to look into this more as that statefile.json file is on the broker which is also the same node as where the shared plan dbs are saved to.  So.. Should be able to grab that file for restoration as well.  Will update shortly once I do more research.

**Comment by kelapure** [comment]
Any update on this . One of our customers really needs this.

**Comment by calebwashburn** [comment]
This issue should be resolved with latest version of the plugin v0.0.13.  This will not extract the statefile.json as well as use for a restore.

**Comment by kelapure** [comment]
Thanks Caleb!

On Mon, Jun 6, 2016 at 11:39 PM, Caleb Washburn <notifications@github.com>
wrote:

> This issue should be resolved with latest version of the plugin v0.0.13.
> This will not extract the statefile.json as well as use for a restore.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pivotalservices/cfops-redis-plugin/issues/1#issuecomment-224163417>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAMmt9j8uBDI4ZAHD7TY9lTHdvKPxfgkks5qJOfrgaJpZM4IfkIu>
> .
>



-- 
Pivotal CF Architect
rkelapure@pivotal.io
cell: 9197242524
